### ISSUE TITLE
Icon font display error

### ISSUE THREAD

**Issue by wangeguo** [amphitheatre-app/desktop#61]
| Before (Expected)  iced_aw: 0.7.0 | After (Wrong) iced_aw: 0.8.0 |
| ------------- | ------------- |
|![截屏2024-02-26 18 36 56](https://github.com/iced-rs/iced_aw/assets/146697/71eaa0a3-1431-4261-a6aa-5c07083be447)|![截屏2024-02-26 18 36 37](https://github.com/iced-rs/iced_aw/assets/146697/f2fb35ca-af71-45b4-9abc-6e14059b9e1f)|

`BootstrapIcon::ChevronExpand`, `BootstrapIcon::Plus` and `BootstrapIcon::Box`

**Comment by EjembiEmmanuel** [comment]
@wangeguo can I work on this?

**Comment by wangeguo** [comment]
> @wangeguo can I work on this?

Of course, You're very welcome.

**Comment by EjembiEmmanuel** [comment]
Great! I've installed the app on my local machine but I'm getting an error (refer to the shared screenshots). Can you help with this?

![Screenshot from 2024-04-08 15-59-34](https://github.com/amphitheatre-app/desktop/assets/83036156/28ba6526-333b-4765-a32f-b811bb7f322a)
![Screenshot from 2024-04-08 15-58-39](https://github.com/amphitheatre-app/desktop/assets/83036156/a2d38f9d-4791-4353-b38e-fa478ca65826)

**Comment by wangeguo** [comment]
> Great! I've installed the app on my local machine but I'm getting an error (refer to the shared screenshots). Can you help with this?

Since your current context is default, which connects to the local network, and you don't have an amp server, it will show a connect error. This is as expected .

I'll email you my own test server and you add it to your configuration as per the following documentation.
https://docs.amphitheatre.app/cli/context/

**Comment by EjembiEmmanuel** [comment]
Alright, thank you! I've been able to get it to work

**Comment by EjembiEmmanuel** [comment]
I've been trying to understand the issue and what I need to do to fix it but I can't seem to arrive at a definite conclusion. Can you please provide more info about the issue?

**Comment by wangeguo** [comment]
> I've been trying to understand the issue and what I need to do to fix it but I can't seem to arrive at a definite conclusion. Can you please provide more info about the issue?

After upgrading, due to font loading issues, the icons that are now displayed may "drift", causing the icons to display incorrectly. It may be necessary to refer to other projects to load the fonts correctly.

**Comment by EjembiEmmanuel** [comment]
Alright

**Comment by wangeguo** [comment]
Sorry, but after I upgraded to iced_aw v0.9.3, I inadvertently realised that it was a conflict of fonts on my local computer that was causing the problem.

**Comment by EjembiEmmanuel** [comment]
That's OK.
